create table public.daily_health_tips (
  id bigint generated by default as identity,
  date date not null,
  species text not null,
  tip_text text not null,
  created_at timestamp with time zone not null default now(),
  constraint daily_health_tips_pkey primary key (id),
  constraint daily_health_tips_date_species_key unique (date, species)
) tablespace pg_default; 